### ISSUE TITLE
How to display posts on FIRST page?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#6]
Hi, can you help to take a look at my blog: [https://longervision.ca/](https://longervision.ca/) ?

My posts are all here [https://longervision.ca/posts/](https://longervision.ca/posts/). But, I wanna the FIRST 3 posts shown on the FIRST page. How to deal with that? Thank you ...

**Comment by rafed** [comment]
I think there is a configuration error the way the posts have been placed in the folder is wrong. Ideally, the website should create links for both the "home" page and the "posts" page from the post directory.

I can see there is a URL error, as the images are not being displayed on the home page.  There is a typo here: logervision.ca/.......

Can you provide me a link to your repo so that I can check whether the project structuring is ok?
